Exercise 3: Identifyng Data Types

For the datasets from the previous exercise, categorize each column of it as either quantitative or qualitative and explain your reasoning.

In [1]:
import pandas as pd

df_sleep = pd.read_csv('../Ex_2/sleep.csv')
df_mental = pd.read_csv('../Ex_2/mental_health.csv')
df_credit = pd.read_csv('../Ex_2/credit.csv')

print("Datasets loaded successfully from the Ex_2 folder!")

Datasets loaded successfully from the Ex_2 folder!

/var/folders/11/01wml45d32l3bgdl2z4gyjth0000gn/T/ipykernel_31643/1696314057.py:4: DtypeWarning: Columns (0: Bipolar disorder (%), 1: Eating disorders (%)) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mental = pd.read_csv('../Ex_2/mental_health.csv')

In [2]:
df_sleep.info()

<class 'pandas.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person ID                374 non-null    int64
 1   Gender                   374 non-null    str
 2   Age                      374 non-null    int64
 3   Occupation               374 non-null    str
 4   Sleep Duration           374 non-null    float64
 5   Quality of Sleep         374 non-null    int64
 6   Physical Activity Level  374 non-null    int64
 7   Stress Level             374 non-null    int64
 8   BMI Category             374 non-null    str
 9   Blood Pressure           374 non-null    str
 10  Heart Rate               374 non-null    int64
 11  Daily Steps              374 non-null    int64
 12  Sleep Disorder           155 non-null    str
dtypes: float64(1), int64(7), str(5)
memory usage: 38.1 KB

In [22]:

print("--- Sleep Dataset Types ---")
print(df_sleep.dtypes)

--- Sleep Dataset Types ---
Person ID                      str
Gender                         str
Age                          int64
Occupation                     str
Sleep Duration             float64
Quality of Sleep             int64
Physical Activity Level      int64
Stress Level                 int64
BMI Category                   str
Blood Pressure                 str
Heart Rate                   int64
Daily Steps                  int64
Sleep Disorder                 str
dtype: object

In [23]:
quant_sleep = df_sleep.select_dtypes(include=['number']).columns.tolist()
qual_sleep = df_sleep.select_dtypes(exclude=['number']).columns.tolist()

print(f"Quantitative = {quant_sleep}")
print(f"\nQualitative = {qual_sleep}")

Quantitative = ['Age', 'Sleep Duration', 'Quality of Sleep', 'Physical Activity Level', 'Stress Level', 'Heart Rate', 'Daily Steps']

Qualitative = ['Person ID', 'Gender', 'Occupation', 'BMI Category', 'Blood Pressure', 'Sleep Disorder']

In [6]:
df_mental.info()

<class 'pandas.DataFrame'>
RangeIndex: 108553 entries, 0 to 108552
Data columns (total 11 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   index                      108553 non-null  int64
 1   Entity                     108553 non-null  str
 2   Code                       103141 non-null  str
 3   Year                       108553 non-null  str
 4   Schizophrenia (%)          25875 non-null   str
 5   Bipolar disorder (%)       19406 non-null   object
 6   Eating disorders (%)       100236 non-null  object
 7   Anxiety disorders (%)      6468 non-null    float64
 8   Drug use disorders (%)     6468 non-null    float64
 9   Depression (%)             6468 non-null    float64
 10  Alcohol use disorders (%)  6468 non-null    float64
dtypes: float64(4), int64(1), object(2), str(4)
memory usage: 9.1+ MB

In [15]:
df_mental.head()

,index,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260

In [24]:
print("--- Mental Health Data Types ---")
print(df_mental.dtypes)

--- Mental Health Data Types ---
index                            str
Entity                           str
Code                             str
Year                             str
Schizophrenia (%)                str
Bipolar disorder (%)          object
Eating disorders (%)          object
Anxiety disorders (%)        float64
Drug use disorders (%)       float64
Depression (%)               float64
Alcohol use disorders (%)    float64
dtype: object

In [27]:
df_mental['index'] = df_mental['index'].astype(str)

quant_mental = df_mental.select_dtypes(include=['number']).columns.tolist()

qual_mental = df_mental.select_dtypes(exclude=['number']).columns.tolist()

print(f"Quantitative: {quant_mental}")
print(f"\nQualitative: {qual_mental}")

Quantitative: ['Anxiety disorders (%)', 'Drug use disorders (%)', 'Depression (%)', 'Alcohol use disorders (%)']

Qualitative: ['index', 'Entity', 'Code', 'Year', 'Schizophrenia (%)', 'Bipolar disorder (%)', 'Eating disorders (%)']

In [28]:
df_credit.info()

<class 'pandas.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Gender          690 non-null    int64
 1   Age             690 non-null    float64
 2   Debt            690 non-null    float64
 3   Married         690 non-null    int64
 4   BankCustomer    690 non-null    int64
 5   Industry        690 non-null    str
 6   Ethnicity       690 non-null    str
 7   YearsEmployed   690 non-null    float64
 8   PriorDefault    690 non-null    int64
 9   Employed        690 non-null    int64
 10  CreditScore     690 non-null    int64
 11  DriversLicense  690 non-null    int64
 12  Citizen         690 non-null    str
 13  ZipCode         690 non-null    int64
 14  Income          690 non-null    int64
 15  Approved        690 non-null    str
dtypes: float64(3), int64(9), str(4)
memory usage: 86.4 KB

In [29]:
df_credit.head()

,Gender,Age,Debt,Married,BankCustomer,Industry,Ethnicity,YearsEmployed,PriorDefault,Employed,CreditScore,DriversLicense,Citizen,ZipCode,Income,Approved
0,1,30.83,0.000,1,1,Industrials,White,1.25,1,1,1,0,ByBirth,202,0,1
1,0,58.67,4.460,1,1,Materials,Black,3.04,1,1,6,0,ByBirth,43,560,1
2,0,24.50,0.500,1,1,Materials,Black,1.50,1,0,0,0,ByBirth,280,824,1
3,1,27.83,1.540,1,1,Industrials,White,3.75,1,1,5,1,ByBirth,100,3,1
4,1,20.17,5.625,1,1,Industrials,White,1.71,1,0,0,0,ByOtherMeans,120,0,1

In [31]:

cols_to_fix = ['ZipCode', 'PriorDefault', 'Employed'] 

for col in cols_to_fix:
    if col in df_credit.columns:
        df_credit[col] = df_credit[col].astype(str)

quant_credit = df_credit.select_dtypes(include=['number']).columns.tolist()
qual_credit = df_credit.select_dtypes(exclude=['number']).columns.tolist()

print(f"Quantitative: {quant_credit}")
print(f"Qualitative: {qual_credit}")

Quantitative: ['Age', 'Debt', 'YearsEmployed', 'CreditScore', 'Income']
Qualitative: ['Gender', 'Married', 'BankCustomer', 'Industry', 'Ethnicity', 'PriorDefault', 'Employed', 'DriversLicense', 'Citizen', 'ZipCode', 'Approved']

Reasons:

Quantitative: These columns represent measurable magnitudes or counts, such as Age, Sleep Duration, and Income. They are categorized as quantitative because their numerical values exist on a scale where mathematical operations—like calculating an average or a sum provide meaningful insights into the data's physical or financial properties.

Qualitative: These columns represent descriptive labels or characteristics, such as Gender, Country, Zip Code, and Binary (0/1) flags. They are categorized as qualitative because they function as nominal identifiers to group observations. Even when they contain digits, performing arithmetic on them (like adding two Zip Codes) is mathematically meaningless because they identify "what kind" rather than "how much.